config/routes.rb
Rails.application.routes.draw do
    resources :neighborhoods

  resources :users

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :favorites, only: [:create, :destroy]

  root 'neighborhoods#index'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :favorites
  has_many :neighborhoods, through: :favorites

  NULL_ATTRS = %w( commute_address commute_city )
  before_save :nil_if_blank

  def nil_if_blank
    NULL_ATTRS.each { |attr| self[attr] = nil if self[attr].blank? }
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def self.find_by_slug(slug)
    User.all.find_by(slug: slug)
  end

  def formatted_first_name
    name.split.first.capitalize
  end

  def get_favorite_by_neighborhood(neighborhood)
    favorites.find{|favorite| favorite.neighborhood_id == neighborhood.id}
  end

  def average_buy_price_of_favorites
    prices = neighborhoods.map{|neighborhood| neighborhood.median_buy_price}
    sum = prices.inject(:+)
    average = sum / prices.size
    average.round
  end

  def average_rent_price_of_favorites
    prices = neighborhoods.map{|neighborhood| neighborhood.median_rental_price_integer}
    sum = prices.inject(:+)
    average = sum / prices.size
    average.round
  end

  def average_price_string(price_int)
    formatted_string = "$"
    formatted_array = []
    unformatted_string = price_int.to_s
    #binding.pry
    string_array = unformatted_string.split("")
    while string_array.length >= 4
      3.times do
        formatted_array.unshift(string_array.pop)
      end
      formatted_array.unshift(",")
    end
    while string_array.length > 0
      formatted_array.unshift(string_array.pop)
    end
    formatted_string << (formatted_array.join)
    formatted_string
  end


  def in_rental_price_range
    Neighborhood.where(median_rental_price_integer: min_rent_price..max_rent_price)
  end

  def in_buy_price_range
    Neighborhood.where(median_buy_price: min_buy_price..max_buy_price)
  end
  
  def similar_to_favorites_buy_price
    delta = average_buy_price_of_favorites / 20
    results = Neighborhood.select{|neighborhood| neighborhood.median_buy_price.between?((average_buy_price_of_favorites - delta), (average_buy_price_of_favorites + delta)) && !self.neighborhoods.include?(neighborhood)}
    results.sample(12)
  end

  def similar_to_favorites_rent_price
    delta = average_rent_price_of_favorites / 15
    results = Neighborhood.select{|neighborhood| neighborhood.median_rental_price_integer.between?((average_rent_price_of_favorites - delta), (average_rent_price_of_favorites + delta)) && !self.neighborhoods.include?(neighborhood)}
    results.sample(12)
  end

  def liked_boroughs
    liked_boroughs = []
    if likes_manhattan
      liked_boroughs << Borough.where(name: "Manhattan").first
    end
    if likes_brooklyn
      liked_boroughs << Borough.where(name: "Brooklyn").first
    end
    if likes_queens
      liked_boroughs << Borough.where(name: "Queens").first
    end
    liked_boroughs
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @rental_counter = 0
    @buying_counter = 0
  end

  def edit
    @user = User.find(params[:id])
    if @user.commute_address
      @commute_place = @user.commute_address
      @address_value = :value
    else
      @commute_place = "e.g. 11 Broadway"
      @commute_value = :placeholder
    end
    if @user.commute_city
      @city = @user.commute_city
      @city_value = :value
    else
      @city = "e.g. New York"
      @city_value = :placeholder
    end
  end

  def update
    #binding.pry
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to(:back)
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :commute_address, :commute_city, :want_to_rent, :want_to_buy, :min_rent_price, :max_rent_price, :min_buy_price, :max_buy_price, :likes_manhattan, :likes_brooklyn, :likes_queens)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_recommendations.html.erb
	
		
		<div class="row">
		<% if user.neighborhoods.size > 0 %>
			<h3>Neighborhoods Similar in Price</h3>
			<% user.similar_to_favorites_by_price.each do |neighborhood| %>
				<div class="col-md-3" style='padding: 0; background-image: url("<%= image_url(neighborhood.user_favorite_photo_url)%>"); background-size: cover; background-position: center; background-repeat: no-repeat; height: 270px;'>
					<h4 style='color: black; background:rgba(55,55,55,.7); margin: 0; width: 100%; padding: 10px;'><%= link_to "#{neighborhood.name}, #{neighborhood.borough}", neighborhood_path(neighborhood) %></h4>
				</div>
			<% end %>
		<% end %>
		</div>

app/views/users/edit.html.erb
<h1>Your Profile</h1>

<%= form_for(@user, :html => {:roll => "form"}) do |f| %>
	<div class="form-group">
	<%= f.label :username %><br>
  <%= f.text_field :username, value: @user.username %><br>
  </div>
  <div class="form-group">
  <%= f.label :email %><br>
  <%= f.text_field :email, value: @user.email %><br>
  </div>
  <div class="form-group">
  <%= f.label "Where you commute to" %>:<br>
  <%= f.label "Street Address" %><br>
  <%= f.text_field :commute_address, @commute_value => @commute_place %><br>
  <%= f.label "City" %><br>
  <%= f.text_field :commute_city, @city_value => @city %><br>
  </div>
  <%= f.submit "Update" %>
<% end %>

app/views/users/show.html.erb
<div class="row" style="margin-top: 70px;">
<div class="container">
	<div class="col-lg-12 ">
    <div class="title text-center">
      <h1>Your Favorites</h1>
      <hr/>
    </div>
  </div>
  <div class="row" style="margin-top:-20px">
	<% if @user.favorites.size >= 1%>
	<div class="pull-right">
	<% if @user.want_to_buy %>
	<h3>Average Buying Price: <%= @user.average_price_string(@user.average_buy_price_of_favorites) %></h3>
	<% end %>
	<% if @user.want_to_rent %>
	<h3>Average Rental Price: <%= @user.average_price_string(@user.average_rent_price_of_favorites) %></h3>
	<% end %>
	</div>
	<% end %>
	
	<br>
	</div>
		<div class="row">
	<% @user.neighborhoods.each do |neighborhood| %>
		<div class="col-md-4" style='padding: 0; background-image: url("<%= image_url(neighborhood.photo_url)%>"); background-size: cover; background-position: center; background-repeat: no-repeat; height: 270px;'>
			<h5 style='color: black; background:rgba(55,55,55,.7); margin: 0; width: 100%; padding: 10px;'><%= link_to "#{neighborhood.name}, #{neighborhood.borough.name}", neighborhood_path(neighborhood) %> <%= link_to "♥", favorite_path(@user.get_favorite_by_neighborhood(neighborhood)), method: :delete, :class => "btn btn-xs btn-primary pull-right" %></h5>
		</div>
	<% end %>
	</div>
	<% if @user.favorites.size >= 1%>
		<% if @user.want_to_buy %>
			<h3>Neighborhoods Similar in Ownership Price</h3>
			<div class="row">
			<% @user.similar_to_favorites_buy_price.each do |neighborhood| %>
				<div class="col-md-2" style='padding: 0; background-image: url("<%= image_url(neighborhood.photo_url)%>"); background-size: cover; background-position: center; background-repeat: no-repeat; height: 270px;'>
					<h5 style='color: black; background:rgba(55,55,55,.7); margin: 0; width: 100%; padding: 10px;'><%= link_to "#{neighborhood.name}, #{neighborhood.borough.name}", neighborhood_path(neighborhood) %></h5>
				</div>
			<% end %>
			</div>
		<% end %>
		<% if @user.want_to_rent %>
			<h3>Neighborhoods Similar in Rent</h3>
			<div class="row">
			<% @user.similar_to_favorites_rent_price.each do |neighborhood| %>
				<div class="col-md-2" style='padding: 0; background-image: url("<%= image_url(neighborhood.photo_url)%>"); background-size: cover; background-position: center; background-repeat: no-repeat; height: 270px;'>
					<h5 style='color: black; background:rgba(55,55,55,.7); margin: 0; width: 100%; padding: 10px;'><%= link_to "#{neighborhood.name}, #{neighborhood.borough.name}", neighborhood_path(neighborhood) %></h5>
				</div>
		<% end %>
		</div>
		<% end %>
	<% end %>
	<%if @user.min_buy_price && @user.max_buy_price && (@user.want_to_buy || @user.want_to_buy == @user.want_to_rent) %>

			<div class="row">
			<h3>Neighborhoods In Your Buy Price Range</h3>
			
			<% @user.in_buy_price_range.each do |neighborhood| %>
				<% if (@user.liked_boroughs.include? neighborhood.borough) && (@buying_counter < 12) %>
				<div class="col-md-2" style='padding: 0; background-image: url("<%= image_url(neighborhood.photo_url)%>"); background-size: cover; background-position: center; background-repeat: no-repeat; height: 270px;'>
					<h5 style='color: black; background:rgba(55,55,55,.7); margin: 0; width: 100%; padding: 10px;'><%= link_to "#{neighborhood.name}, #{neighborhood.borough.name}", neighborhood_path(neighborhood) %></h5>
				</div>
				<% @buying_counter += 1 %>
				<% end %>
			<% end %>
			</div>

	<% end %>

	<%if @user.min_rent_price && @user.max_rent_price && (@user.want_to_rent || @user.want_to_buy == @user.want_to_rent) %>

			<div class="row">
			<h3>Neighborhoods In Your Rental Price Range</h3>
			<% @user.in_rental_price_range.each do |neighborhood| %>
				<% if (@user.liked_boroughs.include? neighborhood.borough) && (@rental_counter < 12) %>
					<div class="col-md-2" style='padding: 0; background-image: url("<%= image_url(neighborhood.photo_url)%>"); background-size: cover; background-position: center; background-repeat: no-repeat; height: 270px;'>
						<h5 style='color: black; background:rgba(55,55,55,.7); margin: 0; width: 100%; padding: 10px;'><%= link_to "#{neighborhood.name}, #{neighborhood.borough.name}", neighborhood_path(neighborhood) %></h5>
					</div>
					<% @rental_counter += 1 %>
				<% end %>
			<% end %>
			</div>

	<% end %>
</div>	
</div>
<div class="credits text-center" style="
    bottom:0; text-align:center; width:100%; background-color: rgba(255, 255, 255, 0.5);">Made with <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color:red;"></span> At <a href="http://www.flatironschool.com" target="_blank" style="text-decoration:none;">The Flatiron School</a>, NYC  
</div>