config/routes.rb
Rails.application.routes.draw do
    resources :neighborhoods

  resources :users

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :favorites, only: [:create, :destroy]

  root 'neighborhoods#index'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/neighborhood.rb
require 'open-uri'
require 'date'
require 'flickr.rb'

class Neighborhood < ActiveRecord::Base
  belongs_to :borough
  has_many :favorites
  has_many :users, through: :favorites
  has_many :restaurants
  has_many :bars

  

  YELP_CLIENT = Yelp::Client.new({ consumer_key: ENV["YELP_CONSUMER_KEY"],
                                consumer_secret: ENV["YELP_CONSUMER_SECRET"],
                                token: ENV["YELP_TOKEN"],
                                token_secret: ENV["YELP_TOKEN_SECRET"]
                              })


  def urlified_name
    name.gsub(" ", "+")
  end

  def get_week
    week = Date.today.cweek
    if week == 53
        week = 52
    end
    week
  end

  def get_year
    Date.today.year
  end

  def find_50th_percentile
    type = "json"
    # the nytimes api call has to ask for get_week - 1 because of the following error: {"status":"ERROR","copyright":"Copyright (c) 2014 The New York Times Company.  All Rights Reserved.","errors":["Invalid Date: 2014-11-24.  Date value has to be earlier than today.","Not Found"],"results":[]}
    url = "http://api.nytimes.com/svc/real-estate/v2/listings/percentile/50.#{type}?date-range=#{get_year}-W#{get_week - 1}&geo-extent-level=neighborhood&geo-extent-value=#{urlified_name}&api-key=#{ENV["NY_TIMES_API_KEY"]}"
    info_hash = JSON.load(open(url))
    info_hash["results"][0]["listing_price"]
  end

  def self.persist_median_buy_prices
    Neighborhood.all.each do |neighborhood|
      sleep(0.1)
      money_string = neighborhood.find_50th_percentile
      result = money_string.gsub(/[$,]/, "").to_i
      neighborhood.update(median_buy_price: result)
    end
  end

  def self.remove_duplicates
    Neighborhood.all.each do |neighborhood|
      copies =  Neighborhood.all.where(name: neighborhood.name)
      while copies.size > 1
        copies.last.destroy
        copies =  Neighborhood.all.where(name: neighborhood.name)
      end
    end
  end

  def get_yelp_top_three_bars
    info = []
    params = { term: 'bar',
               limit: 3,
               sort: 2 # sort by rating
         }
    results = YELP_CLIENT.search("#{name}, New York", params).businesses
    results.each do |result|
      temp_hash = {}
      temp_hash[:name] = result.name
      temp_hash[:address] = result.location.address[0]
      temp_hash[:url] = result.url
      temp_hash[:stars_img] = result.rating_img_url_large
      info << temp_hash
    end
    info
  end

  def get_yelp_top_three_restaurants
    info = []
    params = { term: 'restaurant',
               limit: 3,
               sort: 2 # sort by rating
         }
    results = YELP_CLIENT.search("#{name}, New York", params).businesses
    results.each do |result|
      temp_hash = {}
      temp_hash[:name] = result.name
      temp_hash[:address] = result.location.address[0]
      temp_hash[:url] = result.url
      temp_hash[:stars_img] = result.rating_img_url_large
      info << temp_hash
    end
    info
  end

 
  def find_se_rentals
      url = "http://streeteasy.com/nyc/api/rentals/data?criteria=area:#{urlified_name}-#{borough}\|&key=#{ENV["SE_API_KEY"]}&format=json"
      encoded_url = URI.encode(url)
      info_hash = JSON.load(open(encoded_url))

      {median_price: info_hash["median_price"], search_url: info_hash["search_url"]}
  end

  def noko_listing
      se_hash = find_se_rentals
      ret_hash = {}
      listings_page = Nokogiri::HTML(open(se_hash[:search_url]))

      if listings_page.css(".left-two-thirds .photo img").first
        if listings_page.css(".left-two-thirds .photo img")[2]
          ret_hash[:img_url_1] = listings_page.css(".left-two-thirds .photo img")[2].attributes["data-original"].value
        end
        if listings_page.css(".left-two-thirds .photo img")[3]
          ret_hash[:img_url_2] = listings_page.css(".left-two-thirds .photo img")[3].attributes["data-original"].value
        end
        if listings_page.css(".left-two-thirds .photo img")[4]
          ret_hash[:img_url_3] = listings_page.css(".left-two-thirds .photo img")[4].attributes["data-original"].value
        end
      else
        ret_hash[:img_url_1] = "apt-stock-photo-1.jpg"
        ret_hash[:img_url_2] = "apt-stock-photo-2.jpg"
        ret_hash[:img_url_3] = "apt-stock-photo-3.jpg"
      end

      root_url = "http://streeteasy.com"
        
      # was janky to get nokogiri to pull links and images from same listing, hence the seemingly random array values  
      if listings_page.css(".details-title a")[4]
        append_url_1 = listings_page.css(".details-title a")[4].attributes["href"].value
        ret_hash[:listing_url_1] = root_url + append_url_1
        if listings_page.css(".price")[2]
          ret_hash[:monthly_rent_1] = listings_page.css(".price")[2].children.text
        end
      end

      if listings_page.css(".details-title a")[6]
        append_url_2 = listings_page.css(".details-title a")[6].attributes["href"].value
        ret_hash[:listing_url_2] = root_url + append_url_2
        if listings_page.css(".price")[3]
          ret_hash[:monthly_rent_2] = listings_page.css(".price")[3].children.text
        end
      end

      if listings_page.css(".details-title a")[8]
        append_url_3 = listings_page.css(".details-title a")[8].attributes["href"].value
        ret_hash[:listing_url_3] = root_url + append_url_3
        if listings_page.css(".price")[4]
          ret_hash[:monthly_rent_3] = listings_page.css(".price")[4].children.text
        end
      end
      
      ret_hash[:search_url] = se_hash[:search_url]
      ret_hash[:median_rent] = prettify_median_price(se_hash[:median_price])
      ret_hash[:median_rent_integer] = se_hash[:median_price]
      ret_hash
  end


  def prettify_median_price(price)
    formatted_string = "$"
    formatted_array = []
    unformatted_string = price.to_s
    #binding.pry
    string_array = unformatted_string.split("")
    while string_array.length >= 4
      3.times do
        formatted_array.unshift(string_array.pop)
      end
      formatted_array.unshift(",")
    end
    while string_array.length > 0
      formatted_array.unshift(string_array.pop)
    end
    formatted_string << (formatted_array.join)
    formatted_string
  end

  def twitterified_name
    new_name = name.gsub(" ", "")
    # new_name + "nyc"
  end

  def get_tweets
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV["TWITTER_API_KEY"]
      config.consumer_secret     = ENV["TWITTER_CONSUMER_SECRET"]
    end
    tweets = []
    client.search("##{twitterified_name} #nyc").each do |tweet|
      tweets << tweet
      if tweets.count == 5
        return tweets
      end
    end
    if tweets.count == 0
      client.search("##{borough} #nyc").each do |tweet|
        tweets << tweet
        if tweets.count == 5
          return tweets
        end
      end
    end
    return tweets
  end

  def get_flickr
    FlickRaw.api_key = ENV["FLICKR_API_KEY"]
    FlickRaw.shared_secret = ENV["FLICKR_SHARED_SECRET"]
    # flickr_place = flickr.places.find(:query => "#{name}, New York")
    # place_id = flickr_place[0].place_id
    place_id = FLICKR_PLACE_IDS[name]
    if place_id != "NO PICTURE FOUND"
      photo_hash = flickr.photos.search(:text => name, :place_id => place_id, :per_page => '1', :extras => 'url_o')
      photo_url = photo_hash[0]["url_o"]
      return photo_url
    end
    return nil
  end

  def slug
    name.gsub(" ", "-").downcase
  end

  def user_favorite_photo_url
    FLICKR_PHOTO_URLS[name] || "#{slug}.jpg"
  end

  def self.get_flickr_place_ids
    place_ids = {}
    FlickRaw.api_key = ENV["FLICKR_API_KEY"]
    FlickRaw.shared_secret = ENV["FLICKR_SHARED_SECRET"]
    Neighborhood.all.each do |neighborhood|
      sleep(0.1)
      flickr_places = flickr.places.find(:query => "#{neighborhood.name}, New York")
      if flickr_places
        flickr_places.each do |place|
          if has_photo?(place, neighborhood.name)
            place_ids[neighborhood.name] = place.place_id
            break
          end
        end
        place_ids[neighborhood.name] ||= "NO PICTURE FOUND"
      else
        place_ids[neighborhood.name] = "NO FLICKR PLACE FOUND"
      end
    end
    place_ids
  end

  def self.has_photo?(flickr_place, name)
    FlickRaw.api_key = ENV["FLICKR_API_KEY"]
    FlickRaw.shared_secret = ENV["FLICKR_SHARED_SECRET"]
    place_id = flickr_place.place_id
    sleep(0.1)
    photos = flickr.photos.search(:text => name, :place_id => place_id, :per_page => '1', :extras => 'url_o')
    if photos
      photos.each do |photo|
        if photo
          photo_url = photo["url_o"]
          return photo_url && (photo_url.size > 1)
        end
      end
    end
    return false
  end

  def self.get_photo_urls_from_place_ids
    photo_urls = {}
    Neighborhood.all.each do |neighborhood|
      photo_urls[neighborhood.name] = neighborhood.get_flickr
    end
    photo_urls
  end

  def self.get_neighborhoods_without_photos
    FLICKR_PHOTO_URLS.select{|name, url| url == nil}.keys
  end


  def get_google_directions(commute_address)
    origin = urlified_name + ",NY"
    destination = commute_address.gsub(" ", "+") + ",NY"

    "https://www.google.com/maps/embed/v1/directions?key=#{ENV["GMAPS_API_KEY"]}&origin=#{origin}&destination=#{destination}&mode=transit"
  end

end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
    def index
        @manhattan_neighborhoods = Borough.find_by(name: "Manhattan").neighborhoods
        @brooklyn_neighborhoods = Borough.find_by(name: "Brooklyn").neighborhoods
        @queens_neighborhoods = Borough.find_by(name: "Queens").neighborhoods
        @neighborhood = Neighborhood.new
        if session[:user_id]
            @user = User.find(session[:user_id])
        else
            @user = User.new
        end
        if @user.commute_address
            @commute_place = @user.commute_address
            @address_value = :value
        else
            @commute_place = "e.g. 11 Broadway"
            @commute_value = :placeholder
        end
        if @user.commute_city
            @city = @user.commute_city
            @city_value = :value
        else
            @city = "e.g. New York"
            @city_value = :placeholder
        end
    end

    def show
        @neighborhood = Neighborhood.find(params[:id])
        @favorite_id = nil

        if session[:user_id]
            #binding.pry
            @user = User.find(session[:user_id])
            @user.favorites.each do |favorite|
               @favorite_id = favorite.id if favorite.neighborhood_id == @neighborhood.id
           end
        else
            @user = User.new
        end
    end

    def create
        redirect_to neighborhood_path(params[:neighborhood][:id])
    end

end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/views/neighborhoods/_add_favorite_button.html.erb
<% if user.persisted? %>
	<%= button_to "Add Favorite", favorites_path, params: {"favorite[user_id]" => user.id, "favorite[neighborhood_id]" => neighborhood.id}, :id => "add-favorite-button", :form_class => "add-favorite-form", :class => "btn btn-success pull-right"  %>
<% end %>

app/views/neighborhoods/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= f.text_field :username, placeholder: "username" %>
  <%= f.text_field :email, placeholder: "email address" %>
  <%= f.text_field :commute_address, placeholder: "where do you work?" %>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/neighborhoods/_remove_favorite_button.html.erb
<%= button_to "Remove Favorite", favorite_path(favorite_id), method: :delete, :id => "remove-favorite-button", :form_class => "remove-favorite-form", :class => "btn btn-success pull-right"  %>

app/views/neighborhoods/index-orig.html.erb
<h1>WELCOME TO NYC!</h1>

<select id="borough-selection">
  <option value="hasnt-been-chosen">SELECT A BOROUGH</option>
  <option value="Manhattan">MANHATTAN</option>
  <option value="Brooklyn">BROOKLYN</option>
  <option value="Queens">QUEENS</option>
</select>

<div class="neighborhood-dropdown" id="manhattan-dropdown">
  <%= form_for(@neighborhood) do |f| %>
    <%= f.collection_select :id, @manhattan_neighborhoods,:id,:name, {:prompt => "SELECT A MANHATTAN NEIGHBORHOOD"} %>
      <%= f.submit value: "LET'S SEE THE BUZZ", :class => "see-buzz btn disabled" %>
  <% end %>
</div>

<div class="neighborhood-dropdown" id="brooklyn-dropdown">
  <%= form_for(@neighborhood) do |f| %>
    <%= f.collection_select :id, @brooklyn_neighborhoods,:id,:name, {:prompt => "SELECT A BROOKLYN NEIGHBORHOOD"}%>
    <%= f.submit value: "LET'S SEE THE BUZZ", :class => "see-buzz btn disabled" %>
  <% end %>
</div>

<div class="neighborhood-dropdown" id="queens-dropdown">
  <%= form_for(@neighborhood) do |f| %>
    <%= f.collection_select :id, @queens_neighborhoods,:id,:name, {:prompt => "SELECT A QUEENS NEIGHBORHOOD"}%>
    <%= f.submit value: "LET'S SEE THE BUZZ", :class => "see-buzz btn disabled" %>
  <% end %>
</div>

app/views/neighborhoods/index.html.erb
<div style="background-image: url('images/nyc.jpg'); background-size: cover; background-position: center" class="bg jumbotron">
  <div class="bigHeader text-center">
    <div>
      <hr class="white">
      <h1 class="white uppercase hugetext" style="font-size: 48px;">NYC NEIGHBORHOOD BUZZ</h1>
    </div>

    <div class="dropdown" style="margin-top: 25px;">
      <select id="borough-selection" class="btn-lg btn-danger" style="width:55%;height:45px;">
        <option value="hasnt-been-chosen">SELECT A BOROUGH TO GET STARTED!</option>
        <option value="Manhattan">MANHATTAN</option>
        <option value="Brooklyn">BROOKLYN</option>
        <option value="Queens">QUEENS</option>
      </select>
    </div>

    <div class="neighborhood-dropdown dropdown btn-lg" id="manhattan-dropdown">
      <%= form_for(@neighborhood) do |f| %>
        <%= f.collection_select :id, @manhattan_neighborhoods,:id,:name, {:prompt => "SELECT A MANHATTAN NEIGHBORHOOD"}, :class => "btn-lg" %>
          <%= f.submit value: "LET'S SEE THE BUZZ", :class => "see-buzz btn disabled btn-lg" %>
      <% end %>
    </div>

    <div class="neighborhood-dropdown dropdown btn-lg" id="brooklyn-dropdown">
      <%= form_for(@neighborhood) do |f| %>
        <%= f.collection_select :id, @brooklyn_neighborhoods,:id,:name, {:prompt => "SELECT A BROOKLYN NEIGHBORHOOD"}, :class => "btn-lg" %>
        <%= f.submit value: "LET'S SEE THE BUZZ", :class => "see-buzz btn disabled btn-lg" %>
      <% end %>
    </div>

    <div class="neighborhood-dropdown dropdown btn-lg" id="queens-dropdown">
      <%= form_for(@neighborhood) do |f| %>
        <%= f.collection_select :id, @queens_neighborhoods,:id,:name, {:prompt => "SELECT A QUEENS NEIGHBORHOOD"}, :class => "btn-lg" %>
        <%= f.submit value: "LET'S SEE THE BUZZ", :class => "see-buzz btn disabled btn-lg" %>
      <% end %>
    </div>
  </div>
</div>
<div class="credits text-center" style="position:fixed;
    bottom:0; text-align:center; width:100%; background-color: rgba(255, 255, 255, 0.5);">Made with <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color:red;"></span> At <a href="http://www.flatironschool.com" target="_blank" style="text-decoration:none;">The Flatiron School</a>, NYC  
</div>

app/views/neighborhoods/show-2.html.erb
<div class="container">
<div class="row">

	<h1 class="col-md-8"><%= @neighborhood.name %></h1>
	<h1 class="col-lg-4 animaze fromBottom">

	<div class="cprofile">
    <div class="lightbox-item">
		<% if @favorite_id %>
			<%= render :partial => "remove_favorite_button", :locals => {:favorite_id => @favorite_id} %>
		<% else %>
			<%= render :partial => "add_favorite_button", :locals => {:user => @user, :neighborhood => @neighborhood} %>
		<% end %>
		</div>
	</div>

	</h1>
</div>

<div class="row">
	<div class="col-md-3">
		<h3>Typical Buying Price: <%= @neighborhood.median_buy_price_string %></h3>
		<h3>Median Monthly Rent: <%= @neighborhood.median_rental_price %></h3>

		<h3>New Listings:</h3>

		<%= image_tag("#{@neighborhood.noko_img_url_1}" ) %><br>
		<%= link_to("View This Listing", @neighborhood.noko_listing_url_1, :target => "_blank") %><br>
		<p>Monthly Rent: <%= @neighborhood.noko_monthly_rent_1 %></p><br>

		<%= image_tag("#{@neighborhood.noko_img_url_2}") %><br>
		<%= link_to("View This Listing", @neighborhood.noko_listing_url_2, :target => "_blank") %><br>
		<p>Monthly Rent: <%= @neighborhood.noko_monthly_rent_2 %></p><br>

		<%= image_tag("#{@neighborhood.noko_img_url_3}") %><br>
		<%= link_to("View This Listing", @neighborhood.noko_listing_url_3, :target => "_blank") %><br>
		<p>Monthly Rent: <%= @neighborhood.noko_monthly_rent_3 %></p>

		<%= link_to("More Listings", @neighborhood.noko_search_url, :target => "_blank") %>
	</div>
	<div class="col-md-3">
		<h3 class="pull-right">Recommended Bars</h3>
		<ul>
			<% @neighborhood.bars.each do |bar| %>
				<h4><%= link_to bar.name, bar.url, :target => "_blank" %></h4>
				<%= image_tag("#{bar.stars_img}", height: "15", width: "75") %><br>
				<%= bar.address %><br>
			<% end %>
		</ul>
		<h3 class="pull-right" style="padding-left:35px;">Recommended Restaurants</h3>
		<ul>
			<% @neighborhood.restaurants.each do |restaurant| %>
				<h4><%= link_to restaurant.name, restaurant.url, :target => "_blank" %></h4>
				<%= image_tag("#{restaurant.stars_img}", height: "15", width: "75") %><br>
				<%= restaurant.address %><br>
			<% end %>
		</ul>
	</div>
	<% if @neighborhood.get_tweets %>
	<div class="col-md-3">
		<h3>What People Are Saying About <span class="neighborhood-name"><%= @neighborhood.name %></span></h3>
			<% @neighborhood.get_tweets.each do |tweet| %>
				<blockquote class="twitter-tweet" lang="en" data-cards="hidden">
					<a href="<%= tweet.url %>"></a>
				</blockquote>
				<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
			<% end %>
	</div>
	<% end %>
	<div class="col-md-3">
		<% if @user.persisted? && @user.commute_address %>
			<iframe id="google-map"
	    	frameborder="0" style="border:0"
	    	src="<%=@neighborhood.get_google_directions(@user.commute_address)%>">
	  	</iframe>
	  <% else %>
	  	<div id="map_canvas"></div>
	  <% end %>
	</div>
</div>







<script type="text/javascript">
  $(function(){
    var gmap = new GMap();
    gmap.codeAddress(gmap.address);
  });
</script>

app/views/neighborhoods/show.html.erb
<div class="row" style="margin-top: 70px;">
  <div class="team">
            <div class="container">
                <div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="favorite-button-wrapper">
                                <% if @favorite_id %>
                                    <%= render :partial => "remove_favorite_button", :locals => {:favorite_id => @favorite_id} %>
                                <% else %>
                                    <%= render :partial => "add_favorite_button", :locals => {:user => @user, :neighborhood => @neighborhood} %>
                                <% end %>
                            </div>
                        </div>
                    </div> 
                    <div class="row">   
                        <div class="col-lg-12 ">
                            <div class="title text-center">
                                <h1><%= @neighborhood.name %></h1>
                                <hr/>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-lg-3">
                                    <div class="cprofile" style="height: 500px;overflow: scroll;">
                                        <% if @neighborhood.median_buy_price > 0 %>
                                            <h5>Typical Buying Price: <%= @neighborhood.median_buy_price_string %><br>
                                        <% else %>
                                            <h5></h5>
                                        <% end %>
                                        <% if @neighborhood.median_rental_price_integer > 0 %>
                                            <strong>Median Monthly Rent:</strong> <%= @neighborhood.median_rental_price %><br><br>
                                        <% end %>
                                        New Listings:</h5>

                                        <%= image_tag("#{@neighborhood.noko_img_url_1}" ) %>
                                        <%= link_to("View This Listing", @neighborhood.noko_listing_url_1, :target => "_blank") %><br>
                                        <p>Monthly Rent: <%= @neighborhood.noko_monthly_rent_1 %></p>

                                        <%= image_tag("#{@neighborhood.noko_img_url_2}") %>
                                        <%= link_to("View This Listing", @neighborhood.noko_listing_url_2, :target => "_blank") %><br>
                                        <p>Monthly Rent: <%= @neighborhood.noko_monthly_rent_2 %></p>

                                        <%= image_tag("#{@neighborhood.noko_img_url_3}") %>
                                        <%= link_to("View This Listing", @neighborhood.noko_listing_url_3, :target => "_blank") %><br>
                                        <p>Monthly Rent: <%= @neighborhood.noko_monthly_rent_3 %></p>

                                        <%= link_to("More Listings", @neighborhood.noko_search_url, :target => "_blank") %>
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="cprofile" style="height: 500px;overflow: scroll;">
                                        <h5>Recommended Restaurants</h5>
                                        <ul>
                                          <% @neighborhood.restaurants.each do |restaurant| %>
                                            <h6><%= link_to restaurant.name, restaurant.url, :target => "_blank" %></h6>
                                            <%= image_tag("#{restaurant.stars_img}", style:"width: 70%;") %><br>
                                            <%= restaurant.address %><br>
                                          <% end %>
                                        </ul>
                                        <h5>Recommended Bars</h5>
                                        <ul>
                                          <% @neighborhood.bars.each do |bar| %>
                                            <h6><%= link_to bar.name, bar.url, :target => "_blank" %></h6>
                                            <%= image_tag("#{bar.stars_img}", style:"width: 70%;") %><br>
                                            <%= bar.address %><br>
                                          <% end %>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="cprofile" style="height: 500px;overflow: scroll;">
                                          <% if @neighborhood.get_tweets %>
                                              <h5>What People Are Saying About</h5>
                                              <span class="neighborhood-name"><%= @neighborhood.name %></span>
                                              <% @neighborhood.get_tweets.each do |tweet| %>
                                                <blockquote class="twitter-tweet" lang="en" data-cards="hidden">
                                                  <a href="<%= tweet.url %>"></a>
                                                </blockquote>
                                                <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
                                              <% end %>
                                          <% end %>
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="cprofile" style="height: 500px;overflow: scroll;">
                                        <% if @user.persisted? && @user.commute_address %>
                                          <h5>Your Commute to <%= @neighborhood.name %></h5>
                                            <iframe id="google-map"
                                            frameborder="0" style="border:0;height:100%;"
                                            src="<%=@neighborhood.get_google_directions(@user.commute_address)%>">
                                        </iframe>
                                      <% else %>
                                        <h5><%= @neighborhood.name %> Map</h5>
                                        <div id="map_canvas" style="height:100%;"></div>
                                      <% end %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

</div>
<div class="credits text-center" style="
    bottom:0; text-align:center; width:100%; background-color: rgba(255, 255, 255, 0.5);">Made with <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color:red;"></span> At <a href="http://www.flatironschool.com" target="_blank" style="text-decoration:none;">The Flatiron School</a>, NYC  
</div>

<script type="text/javascript">
  $(function(){
    var gmap = new GMap();
    gmap.codeAddress(gmap.address);
  });
</script>