config/routes.rb
Rails.application.routes.draw do
    resources :neighborhoods

  resources :users

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :favorites, only: [:create, :destroy]

  root 'neighborhoods#index'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/views/layouts/application-orig.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NeighborhoodBuzz</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
  <script src="https://maps.googleapis.com/maps/api/js"></script>
</head>
<body>
	<nav class="nav navbar-inverse navbar-fixed-top" roll="navigation">
    <div class="navbar-header">
      <%= link_to("Neighborhood Buzz", neighborhoods_path, class: "navbar-brand") %>
    </div>
    
    <ul class="nav navbar-nav">
      <% if session[:user_id] %>
        <li>
          <%= link_to("Hello #{@user.username}. See your favorites.", user_path(@user))  %>
        </li>
        <li>
          <%= link_to("Edit Your Profile", edit_user_path(@user))  %>
        </li>
        <li>
          <%= link_to("Logout", logout_path) %>
        </li>
      <% end %>
    </ul>
    <div id="navbar" class="navbar-collapse collapse">
      <%= form_for(User.new, :html => {:class => "navbar-form navbar-right", :roll => "form"}) do |f| %>
        <div class="form-group">
          <%= f.text_field :username, placeholder: "username" %>
        </div>
        <div class="form-group">
          <%= f.text_field :email, placeholder: "email address" %>
        </div>
        <div class="form-group">
          <%= f.text_field :commute_address, placeholder: "where do you work?" %>
        </div>
        <%= f.submit "Sign Up", class: "btn btn-success" %>
      <% end %>
      <%= form_tag(sessions_path, :class => "navbar-form navbar-right", :roll => "form") do %>
        <div class="form-group">
          <input type="text" name="username" placeholder="username" />
        </div>
        <input class="btn btn-success" name="commit" type="submit" value="Sign In">

      <% end %>
    </div>
  </nav>



  <div class="container">

    <div id="alert">
        <% if flash[:notice] %>
           <div class="alert alert-warning"><%= flash[:notice] %></div>
        <% end %>
    </div>
		<%= yield %>

	</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NeighborhoodBuzz</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
  <link href="../css/styles.css" rel="stylesheet">
  <script src="https://maps.googleapis.com/maps/api/js"></script>
</head>
<body>
  <nav class="nav navbar-default navbar-fixed-top" roll="navigation">
      <div class="navbar-header">
        <%= link_to("Neighborhood Buzz", root_path, class: "navbar-brand") %>
      </div>
      <% if session[:user_id] %>
      <ul class="nav navbar-nav">
            <!-- Welcome <strong>?  </strong>! -->
            <li style="margin-left: 50px;"><%= link_to("Welcome, #{current_user.formatted_first_name}! See your favorites.", user_path(@user))  %></li> 

            <li class="dropdown" style="margin-right: 20px;">
              <a href="" class="dropdown-toggle" data-toggle="dropdown">
                Edit Your Profile
                <b class="caret"></b>
              </a>
              <div class="dropdown-menu" style="padding: 10px; width: 150%;">
                <%= form_for(@user, :html => {:roll => "form"}) do |f| %>
                  <div class="form-group">
                  <%= f.label :email %><br>
                  <%= f.text_field :email, value: @user.email %><br>
                  </div>
                  <div class="form-group">
                  <%= f.label "Where you commute to" %>:<br>
                  <%= f.label "Street Address" %><br>
                  <%= f.text_field :commute_address, @commute_value => @commute_place %><br>
                  <%= f.label "City" %><br>
                  <%= f.text_field :commute_city, @city_value => @city %><br>
                  <%= f.check_box(:want_to_rent) %>
                  <%= f.label(:want_to_rent, "looking to rent") %><br>
                  <%= f.label("Rental price range") %><br>
                  <%= f.number_field(:min_rent_price, :style => "width:42%;")%> to <%= f.number_field(:max_rent_price, :style => "width:42%;")%><br>
                  <%= f.check_box(:want_to_buy) %>
                  <%= f.label(:want_to_buy, "looking to buy") %><br>
                  <%= f.label("Buying price range") %><br>
                  <%= f.number_field(:min_buy_price, :style => "width:42%;")%> to <%= f.number_field(:max_buy_price, :style => "width:42%;")%><br>
                  </div>
                  <%= f.label("Boroughs you're interested in") %><br>
                  <%= f.check_box(:likes_manhattan) %>
                  <%= f.label(:likes_manhattan, "Manhattan") %><br>
                  <%= f.check_box(:likes_brooklyn) %>
                  <%= f.label(:likes_brooklyn, "Brooklyn") %><br>
                  <%= f.check_box(:likes_queens) %>
                  <%= f.label(:likes_queens, "Queens") %><br>
                  <%= f.submit "Update" %>
                <% end %>
              </div>
            </li>
  

            <li><%= link_to("Logout", logout_path, id:"sign_out") %></li>

        </ul> 
      <% end %>


        <% if !session[:user_id] %>
          <div class="nav navbar-nav navbar-right">
            <li>
            <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
            </li>
          </div>
        <% end %>
  </nav>


    <div id="alert">
        <% if flash[:notice] %>
           <div class="alert alert-warning"><%= flash[:notice] %></div>
        <% end %>
    </div>

        <%= yield %>

  <div class="container">

  </div>
  <div class="container">
  <div class="row">
  
  </div>
  </div>

</body>
</html>